# .github/workflows/version.yml
name: Git Version

on:
  push:

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/972321173961/locations/global/workloadIdentityPools/gh-reminisce/providers/gh-reminisce-provider'
          service_account: 'gh-reminisce@impactful-mode-268210.iam.gserviceaccount.com'

      - name: Launch cloud-sql-proxy
        run: |-
          curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.4.0/cloud-sql-proxy.linux.amd64
          chmod +x cloud-sql-proxy
          ./cloud-sql-proxy impactful-mode-268210:us-central1:reminisce --gcloud-auth --health-check --port 5432 &
          
          while true; do
            response=$(curl -s -w "%{http_code}" -o /dev/null "http://localhost:9090/readiness")
            if [ "$response" == "200" ]; then
              echo "Endpoint is ready"
              break
            fi          
            echo "Waiting for endpoint to be ready..."
            sleep 5
          done


      - name: test
        run: |-
          curl -v localhost:9090/readiness
          curl -v localhost:5432

      - uses: liquibase-github-actions/update@v4.23.0
        with:
          changelogFile: "db/changelog/changelog-root.yaml"
          url: "jdbc:postgresql://127.0.0.1:5432/postgres"
          password: ${{ secrets.PG_PASSWORD }}
          username: "postgres"


      - name: Set-up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build
        id: build
        run: |-
          ./gradlew test
          ./gradlew jib \
            --image us-east1-docker.pkg.dev/impactful-mode-268210/reminisce/reminisce:${{ steps.version.outputs.version }}

      - name: Deploy to CloudRun
        id: deploy
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: 'reminisce'
          image: us-east1-docker.pkg.dev/impactful-mode-268210/reminisce/reminisce:${{ steps.version.outputs.version }}
          env_vars: |
            PG_PASSWORD=${{ secrets.PG_PASSWORD }}
            SPRING_PROFILES_ACTIVE=staging

      - name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}"'

